### ISSUE TITLE
Purge database parties

### ISSUE THREAD

**Issue by vetom** [lycan-city/werewolf-virtual-cards#33]
Related to #16 is necessary to create a mechanism to remove empty parties or expires one. [This post](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html) might be helpful.

**Comment by Randyjp** [comment]
I'll be taking a shot at this @vetom, will contact you in case I need further clarifications.

**Comment by wovalle** [comment]
Just for the sake of documentation: #15 is needed in order to complete this task.
